language: go
os:
  - osx

osx_image: xcode8

before_install:
  - brew install git-lfs
  - git lfs install --system
  - git lfs pull

sudo: false

go:
  - "1.7"
  - "1.8"
  - "1.9"
  - "1.10"
  - "1.11"
  - tip

script:
  - go test -v ./...
