#!/usr/bin/env python

import argparse
import errno
import os
import subprocess
import sys


SOURCE_ROOT = os.path.abspath(os.path.dirname(os.path.dirname(__file__)))
VENDOR_DIR = os.path.join(SOURCE_ROOT, 'vendor')


def main():
    args = parse_args()
    update_submodules()
    bootstrap_brightray(args.commit, args.url)


def parse_args():
    parser = argparse.ArgumentParser(description='Bootstrap this project')
    parser.add_argument('-c', '--commit', nargs='?', default='HEAD',
                        help='The commit of libchromiumcontent to download.')
    parser.add_argument('url', help='The base URL from which to download '
                        'libchromiumcontent (i.e., the URL you passed to '
                        'libchromiumcontent\'s script/upload script')
    return parser.parse_args()


def update_submodules():
    cwd = os.getcwd()
    os.chdir(SOURCE_ROOT)
    try:
        subprocess.check_call(['git', 'submodule', 'sync', '--quiet'])
        subprocess.check_call(['git', 'submodule', 'update', '--init',
                               '--recursive'])
    finally:
        os.chdir(cwd)


def bootstrap_brightray(commit, url):
    bootstrap = os.path.join(VENDOR_DIR, 'brightray', 'script', 'bootstrap')
    subprocess.check_call([sys.executable, bootstrap, '-c', commit, url])


if __name__ == '__main__':
    sys.exit(main())
