/*
* CODE AUTOMATICALLY GENERATED BY gallium-main
* NEVER EDIT THIS CODE BY HAND
 */
package main

import (
	"os"
	"runtime"

	"github.com/alexflint/gallium"
)

func main() {
	runtime.LockOSThread()
	gallium.RedirectStdoutStderr(os.ExpandEnv("$HOME/Library/Logs/Gallium.log"))

	gallium.Loop(os.Args, New())

}
